language: rust
sudo: false

rust:
  - stable
  - beta
  - nightly

addons:
  apt:
    packages:
      - gfortran

after_success:
  - curl https://markov-chain.github.io/travis/documentation.sh | bash

env:
  global:
    - CRATE_NAME=threed_ice
    - secure: XeHfgEGMLHND/aTY/dUd982F4PBlCg6QscEwlzHBxc8BfoeoxHSniM2Be+sZ78FPa9Bu2BgmDLJWFtuLwXNNQFWMZ27gO6CVhB43wFX1gsAkZzdPZPT0uOpWVcgR3giIH0q1VGyo4PcahiIFH4Wpd6vBYrvvG1CS1sYxfk/7r1j5rsJfw9150Dr5LkIvprWIT8spTDMbnGyEgC+/S60pzAO0Xra9+Nwd9p/W5GFaSLjruMWYsKQYhUroQDt9Nl1NiZ4kFag1yBPLca2a0Z9BZUhlDhhoTSlbXtdlU5uZTd/VP/VmmXXe/ki0Vug7VXTVHuavTL/Zr9NVBjX7eFkbexwrljfpMYXcvjIP8Fyv+lMp+OrKIBC17+JAYID3Hy2ZO3FXdaGh/1wkNUpvE/p/TsHED6n1UExYc0esYrxJqB8nDmoZR4SQNwkd3tXW8Ge9EQtx+7j6s9EhW6Vs6FOKppd0+UDqJhJopsQZyRoBye7mfkdUAx2aPZ+F+CAAS3tL2+RG0d9bP6GMwNy8CA8dbvtgqUiNFWpNH6VZk7A55xD2SbX4r6eriBLMNzQ6qDMS3Xspx/Ljlk10aJazW5yp78stIdyFEVr/0fPRtlaIq16iVyXsIt26amxTyz645PlZ8GsRJ8xgOLwp8BOB6XyRnT4TEEUxotKvUIOnAKWrMCI=

notifications:
  email: false
