language: rust
sudo: false

addons:
  apt:
    packages:
      - gfortran

after_success:
  - curl https://markov-chain.github.io/travis/after_success.sh | CRATE_NAME=threed_ice bash

env:
  global:
    secure: gxPx4fI0TmygFEwXPX2OrHyJNL9X/GS32TOKm2pysXcvNkVq+4XR6M1/gnswpxIA/zHdOAyofr4YBZw/YwCTtRQT8mjuhMmRAC6iDnQs1hIxhwpk/t/Fbk8ulHnIUzbZBv18PCbXu4fcqGIGzR2ypMSvYqLi4xJSLihLaTeVoUrVQcjeaqu/8+0uiPn8mDW0jjOwSKlum7BNT8GEpc3QH2S7jzzdOYEPHwew+RHOjcFux03tlI2ivp1+bSSGQvBGhfaNow3Nm3YHlS23ggFjTZpzMP9qqc4EmpbD5pfUMe/2vO85XEGh0d6W/x6RYs4kKWp/3EPazoijmnR/14dSwWWPo0majkomKfkEQfdRNkE8gbqU2GQUhGd9b43tjneGnGLPoFArSBsDGAXJSUlp4ryMJMrFYp19NUTElpc/Jngmj300G7pWJ/d5ZElc971GazfotekA2LTD9YdWFScJgwI6k2oMKkAJ+OCSyRQqmXGuCYg5iPRG20L0UQAcjhak1I2XsGOjvkt9K3rxOXkLrdsTuCsIvZFXY+VhHBwWnkaJNrSJK2w2rjOvXibukGiHl+1FyyOifMojKtQx9sPNiNPPARNF0wX8TFaH22kqZ7CSf1yluhBN45zN3IOzgryGzEZonutFG+ZtsR1TU/Tti9bY6AR2RN8vBKgT2RUzEo0=

notifications:
  email: false
