[package]
name = "threed-ice"
version = "0.2.0"
authors = ["Ivan Ukhov <ivan.ukhov@gmail.com>"]
license = "MIT"
repository = "https://github.com/simulated-reality/3d-ice"
homepage = "https://github.com/simulated-reality/3d-ice"
documentation = "https://simulated-reality.github.io/3d-ice"
description = "The package provides an interface to 3D-ICE."

[dependencies]
matrix = "*"
threed-ice-sys = "*"

[dev-dependencies]
assert = "*"
fixture = "*"
temporary = "*"
